# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-22 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('passed', models.IntegerField(verbose_name='通过数')),
                ('failed', models.IntegerField(verbose_name='失败数')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('build_time', models.DateTimeField(verbose_name='触发时间')),
            ],
        ),
    ]
