# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-22 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='type',
            field=models.CharField(choices=[('k12-campus', '卡搭校园'), ('k12-100', '网易100分'), ('k12-geek', '卡搭课程'), ('k12-geek-mobile', '卡搭课程app'), ('k12-100-app', '网易100分app')], default='k12-campus', max_length=64, verbose_name='项目'),
        ),
    ]
